spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
#   rabbitmq:
#     host: 127.0.0.1
#     port: 5762
#     username: suyun
#     password: suyun
mybatis:
  type-aliases-package: com.jbf.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
my:
  app-id: is this your coat?yes,it is.Thanks!
# 关闭验证，暴露端点
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
