spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    data-username: root
    data-password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
